#=
================================================================================
                            QGYBJ.jl - Main Module
================================================================================

This module implements the QG-YBJ+ (Quasi-Geostrophic Young-Ben Jelloul Plus)
model for simulating the interaction between near-inertial waves and balanced
ocean eddies.

PHYSICAL BACKGROUND:
--------------------
The QG-YBJ+ model couples two key physical processes:

1. BALANCED FLOW (Quasi-Geostrophic):
   - Governed by the QG potential vorticity (PV) equation
   - Represents mesoscale eddies and geostrophic currents
   - Evolves on the "slow" timescale

2. NEAR-INERTIAL WAVES (NIW):
   - Internal waves with frequencies near the Coriolis frequency f
   - Generated by wind forcing, tides, or other mechanisms
   - Evolves on the "fast" timescale but affects mean flow

KEY EQUATIONS:
--------------
The model solves two coupled equations:

(1) QG Potential Vorticity Evolution:
    ∂q/∂t + J(ψ, q) + J(ψ, qʷ) = dissipation

    where:
    - q = ∇²ψ + (f²/N²)∂²ψ/∂z² is the QG PV
    - ψ is the streamfunction (u = -∂ψ/∂y, v = ∂ψ/∂x)
    - qʷ is the wave feedback on mean flow (Xie & Vanneste 2015)
    - J(a,b) = ∂a/∂x ∂b/∂y - ∂a/∂y ∂b/∂x is the Jacobian

(2) YBJ+ Wave Envelope Evolution:
    ∂B/∂t + J(ψ, B) + B∂ζ/∂t = dispersion + refraction + dissipation

    where:
    - B = L⁺A is the wave envelope in YBJ+ form
    - A is the actual wave amplitude
    - ζ = ∇²ψ is the relative vorticity
    - L⁺ is an elliptic operator relating A and B

NUMERICAL METHODS:
------------------
- Pseudo-spectral in horizontal (FFT-based)
- Second-order finite differences in vertical
- Leapfrog time stepping with Robert-Asselin filter
- Tridiagonal solvers for elliptic inversions
- 2/3 dealiasing rule for nonlinear terms

REFERENCES:
-----------
- Asselin & Young (2019): YBJ+ formulation
- Xie & Vanneste (2015): Wave feedback qʷ
- Young & Ben Jelloul (1997): Original YBJ equation

CODE STRUCTURE:
---------------
- parameters.jl   : Model parameters (QGParams struct)
- grid.jl         : Spatial grid and spectral wavenumbers
- transforms.jl   : FFT planning (serial and parallel)
- physics.jl      : Stratification profiles, N², a_ell coefficients
- elliptic.jl     : Tridiagonal solvers for ψ and A inversions
- operators.jl    : Velocity computation from ψ
- nonlinear.jl    : Jacobians, refraction, wave feedback qʷ
- timestep.jl     : Time integration (Euler, Leapfrog)
- ybj_normal.jl   : Normal YBJ (non-plus) operators
- diagnostics.jl  : Energy diagnostics, omega equation
- model_interface.jl : High-level simulation API
- netcdf_io.jl    : NetCDF input/output
- particles/      : Lagrangian particle advection

GETTING STARTED:
----------------
    using QGYBJ

    # Create configuration
    config = create_simple_config(
        nx=64, ny=64, nz=64,
        dt=0.001, nt=1000,
        output_interval=100
    )

    # Run simulation
    result = run_simple_simulation(config)

================================================================================
=#

module QGYBJ

using LinearAlgebra

# External backends are optional. If you wish to use MPI/PencilArrays/PencilFFTs,
# load them in your environment before using QGYBJ. Serial mode works by default.
@info "MPI/PencilArrays/PencilFFTs not loaded yet. You can still use serial mode."

#=
================================================================================
                              PUBLIC API EXPORTS
================================================================================
The exports are organized by functionality:

1. CORE DATA STRUCTURES:
   - QGParams: All model parameters (physics, numerics, switches)
   - Grid: Spatial grid and spectral wavenumbers
   - State: Prognostic (q, B) and diagnostic (ψ, A, u, v, w) fields

2. PHYSICS ROUTINES:
   - Elliptic solvers: invert_q_to_psi!, invert_B_to_A!, invert_helmholtz!
   - Nonlinear terms: jacobian_spectral!, convol_waqg!, refraction_waqg!, compute_qw!
   - Velocity operators: compute_velocities!, compute_vertical_velocity!

3. TIME STEPPING:
   - first_projection_step!: Forward Euler for initialization
   - leapfrog_step!: Main time integration with Robert-Asselin filter

4. HIGH-LEVEL INTERFACE:
   - QGYBJSimulation, setup_simulation, run_simulation!
   - Configuration builders: create_domain_config, create_model_config, etc.

5. I/O AND DIAGNOSTICS:
   - NetCDF output: ncdump_psi, ncdump_la, OutputManager
   - Energy diagnostics: wave_energy, flow_kinetic_energy
================================================================================
=#

# Public API - Core functionality
export QGParams, Grid, State,
       init_grid, init_state, init_pencil_decomposition!,
       plan_transforms!, setup_parallel_transforms, fft_forward!, fft_backward!,
       compute_wavenumbers!,
       invert_q_to_psi!, compute_velocities!, compute_vertical_velocity!, compute_ybj_vertical_velocity!, compute_total_velocities!, compute_wave_velocities!,
       default_params, setup_model,
       a_ell_ut, dealias_mask,
       invert_B_to_A!, invert_helmholtz!,
       jacobian_spectral!, convol_waqg!, refraction_waqg!, compute_qw!, dissipation_q_nv!, int_factor,
       init_random_psi!,
        first_projection_step!, leapfrog_step!,
        sumB!, compute_sigma, compute_A!,
        omega_eqn_rhs!, wave_energy, flow_kinetic_energy, wave_energy_vavg, slice_horizontal, slice_vertical_xz

# Public API - New user interface
export DomainConfig, StratificationConfig, InitialConditionConfig, OutputConfig, ModelConfig,
       create_domain_config, create_stratification_config, create_initial_condition_config,
       create_output_config, create_model_config,
       QGYBJSimulation, setup_simulation, run_simulation!,
       create_simple_config, run_simple_simulation,
       OutputManager, write_state_file, read_initial_psi, read_initial_waves, read_stratification_profile,
       StratificationProfile, ConstantN, SkewedGaussian, TanhProfile,
       create_stratification_profile, compute_stratification_profile,
       # Legacy I/O compatibility functions (now implemented in netcdf_io.jl)
       ncdump_psi, ncdump_la, ncread_psi!, ncread_la!,
       # Parallel interface
       ParallelConfig, setup_parallel_environment, init_parallel_grid, init_parallel_state,
       # Unified particle advection system (handles both serial and parallel automatically)
       ParticleConfig, ParticleState, ParticleTracker, create_particle_config,
       initialize_particles!, advect_particles!, interpolate_velocity_at_position,
       write_particle_trajectories, read_particle_trajectories, write_particle_snapshot,
       create_particle_output_file, write_particle_trajectories_by_zlevel,
       enable_auto_file_splitting!, finalize_trajectory_files!,
       # Advanced interpolation methods
       InterpolationMethod, TRILINEAR, TRICUBIC, ADAPTIVE, QUINTIC,
       # 3D particle distributions
       ParticleConfig3D, ParticleDistribution, create_particle_config_3d,
       initialize_particles_3d!, UNIFORM_GRID, LAYERED, RANDOM_3D, CUSTOM,
       create_uniform_3d_grid, create_layered_distribution, create_random_3d_distribution, create_custom_distribution

#=
================================================================================
                              MODULE INCLUDES
================================================================================
Files are included in dependency order. Each file is a self-contained module
that is "used" back into the main QGYBJ namespace.
================================================================================
=#

# Core data structures and parameters
include("parameters.jl")    # QGParams: all model parameters
include("grid.jl")          # Grid: spatial coordinates and wavenumbers

# FFT and spectral transforms
include("transforms.jl")    # FFTW planning, fft_forward!, fft_backward!

# Physics and numerical operators
include("physics.jl")       # Stratification N², a_ell coefficient
include("elliptic.jl")      # Tridiagonal solvers for elliptic inversions
include("operators.jl")     # Velocity computation from streamfunction

# Runtime utilities
include("runtime.jl")       # Setup helpers

# Nonlinear terms and tendencies
include("nonlinear.jl")     # Jacobians, refraction, wave feedback qʷ

# Time integration
include("timestep.jl")      # Forward Euler, Leapfrog with Robert-Asselin

# Initial conditions
include("initconds.jl")     # Random and analytic initial conditions

# Normal YBJ (non-plus) operators
include("ybj_normal.jl")    # sumB!, compute_sigma, compute_A! for normal YBJ

# Diagnostics
include("diagnostics.jl")   # Energy diagnostics, omega equation RHS

# High-level user interface
include("model_interface.jl")  # QGYBJSimulation, run_simulation!, etc.
include("netcdf_io.jl")        # NetCDF I/O with legacy compatibility

# Particle advection system (for Lagrangian tracking)
include("particles/unified_particle_advection.jl")  # Particle tracking core
include("particles/particle_io.jl")                  # Particle trajectory I/O

end # module
